apiVersion: v1
ind: ConfigMap
etadata:
 name: nginx-config
 namespace: default
ata:
 nginx.conf: |
   events {
     worker_connections 1024;
   }
   http {
     server {
       listen 80;
       server_name localhost;
        # Health check endpoints
       location /health {
         access_log off;
         return 200 'healthy\n';
       }
        location /ready {
         access_log off;
         return 200 'ready\n';
       }
        location /live {
         access_log off;
         return 200 'alive\n';
       }
        # Default location
       location / {
         root /usr/share/nginx/html;
         index index.html;
       }
     }
   }
